scrape_configs:
# 任意写，建议英文，不要包含特殊字符
- job_name: 'collect-metrics-job'
  # 多久采集一次数据
  scrape_interval: 15s
  # 采集时的超时时间
  scrape_timeout: 10s
  # 采集的端点
  metrics_path: '/actuator/prometheus'
  # 被采集的服务地址，即微服务的ip及端口
  static_configs:
  - targets: ['192.168.10.237:8080']